config/routes.rb
Rails.application.routes.draw do
    root                'static_pages#home'
    get    'help'    => 'static_pages#help'
    get    'about'   => 'static_pages#about'
    get    'aboutus' => 'static_pages#aboutus'
    get    'contact' => 'static_pages#contact'
    get    'allergyimmunology'   => 'static_pages#allergyimmunology'
    get    'anatomicpathology' => 'static_pages#anatomicpathology'
    get    'anatomicclinicalpathology' => 'static_pages#anatomicclinicalpathology'
    get    'anesthesiology' => 'static_pages#anesthesiology'
    get    'bariatricsurgery' => 'static_pages#bariatricsurgery'
    get    'breastsurgery' => 'static_pages#breastsurgery'
    get    'cardiacsurgery' => 'static_pages#cardiacsurgery'
    get    'cardiovasculardisease' => 'static_pages#cardiovasculardisease'
    get    'childadolescentpsychiatry' => 'static_pages#childadolescentpsychiatry'
    get    'childneurology'=> 'static_pages#childneurology'
    get    'clinicalcardiacelectrophysiology' => 'static_pages#clinicalcardiacelectrophysiology'
    get    'clinicalpathology' => 'static_pages#clinicalpathology'
    get    'colonrectalsurgery' => 'static_pages#colonrectalsurgery'
    get    'criticalcaremedicine' => 'static_pages#criticalcaremedicine'
    get    'dentistry' => 'static_pages#dentistry'
    get    'dermatology' => 'static_pages#dermatology'
    get    'diagnosticradiology'=> 'static_pages#diagnosticradiology'
    get    'emergencymedicalservices' => 'static_pages#emergencymedicalservices'
    get    'endocrinology'=> 'static_pages#endocrinology'
    get    'facialplasticreconstrsurgery'=> 'static_pages#facialplasticreconstrsurgery'
    get    'familymedicine' => 'static_pages#familymedicine'
    get    'gastroenterology' => 'static_pages#gastroenterology'
    get    'generalsurgery' => 'static_pages#generalsurgery'
    get    'geriatricmedicine' => 'static_pages#geriatricmedicine'
    get    'gynecologiconcology' => 'static_pages#gynecologiconcology'
    get    'gynecology'=> 'static_pages#gynecology'
    get    'handsurgery'=> 'static_pages#handsurgery'
    get    'headnecksurgery'=> 'static_pages#headnecksurgery'
    get    'hematology'=> 'static_pages#hematology'
    get    'hospiceandpalliativemedicine'=> 'static_pages#hospiceandpalliativemedicine'
    get    'hyperbaricmedicine' => 'static_pages#hyperbaricmedicine'
    get    'infectiousdisease' => 'static_pages#infectiousdisease'
    get    'integrativemedicine'=> 'static_pages#integrativemedicine'
    get    'internalmedicine' => 'static_pages#internalmedicine'
    get    'interventionalcardiology' => 'static_pages#interventionalcardiology'
    get    'maternalfetalmedicine' => 'static_pages#maternalfetalmedicine'
    get    'medicaloncology' => 'static_pages#medicaloncology'
    get    'neonatalperinatalmedicine'=> 'static_pages#neonatalperinatalmedicine'
    get    'nephrology' => 'static_pages#nephrology'
    get    'neurologicalsurgery' => 'static_pages#neurologicalsurgery'
    get    'neurology' => 'static_pages#neurology'
    get    'neuroradiology'=> 'static_pages#neuroradiology'
    get    'nuclearmedicine' => 'static_pages#nuclearmedicine'
    get    'obstetrics' => 'static_pages#obstetrics'
    get    'occupationalmedicine' => 'static_pages#occupationalmedicine'
    get    'ophthalmology' => 'static_pages#ophthalmology'
    get    'oralmaxillofacialsurgery' => 'static_pages#oralmaxillofacialsurgery'
    get    'orthopaedicsurgery' =>  'static_pages#orthopaedicsurgery'
    get    'otolaryngology' => 'static_pages#otolaryngology'
    get    'painmedicinepainmanagement' => 'static_pages#painmedicinepainmanagement'
    get    'pathology' => 'static_pages#pathology'
    get    'pediatricallergyimmunology' => 'static_pages#pediatricallergyimmunology'
    get    'pediatriccardiology' => 'static_pages#pediatriccardiology'
    get    'pediatricdentistry' => 'static_pages#pediatricdentistry'
    get    'pediatricdermatology' => 'static_pages#pediatricdermatology'
    get    'pediatricendocrinology' => 'static_pages#pediatricendocrinology'
    get    'pediatricinfectiousdisease' => 'static_pages#pediatricinfectiousdisease'
    get    'pediatricophthalmology' => 'static_pages#pediatricophthalmology'
    get    'pediatricpulmonology' => 'static_pages#pediatricpulmonology'
    get    'pediatricradiology' => 'static_pages#pediatricradiology'
    get    'pediatricsurgery' => 'static_pages#pediatricsurgery'
    get    'pediatricUrology' => 'static_pages#pediatricUrology'
    get    'pediatrics' => 'static_pages#pediatrics'
    get    'physicalmedicinerehabilitation' => 'static_pages#physicalmedicinerehabilitation'
    get    'plasticreconstructivesurgery' => 'static_pages#plasticreconstructivesurgery'
    get    'podiatry' => 'static_pages#podiatry'
    get    'psychiatry' => 'static_pages#psychiatry'
    get    'pulmonarydiseasemedicine' => 'static_pages#pulmonarydiseasemedicine'
    get    'radiationoncology' => 'static_pages#radiationoncology'
    get    'radiology' => 'static_pages#radiology'
    get    'radiologyneurointerventional' => 'static_pages#radiologyneurointerventional'
    get    'radiologyvascularinterventional' => 'static_pages#radiologyvascularinterventional'
    get    'reproductiveendocrinology' => 'static_pages#reproductiveendocrinology'
    get    'retinaspecialist' => 'static_pages#retinaspecialist'
    get    'rheumatology' => 'static_pages#rheumatology'
    get    'sleepmedicine' => 'static_pages#sleepmedicine'
    get    'spinesurgery' => 'static_pages#spinesurgery'
    get    'sportsmedicine' => 'static_pages#sportsmedicine'
    get    'surgicalcriticalcare' => 'static_pages#surgicalcriticalcare'
    get    'surgicaloncology' => 'static_pages#surgicaloncology'
    get    'thoracicsurgery' => 'static_pages#thoracicsurgery'
    get    'transplanthepatology' => 'static_pages#transplanthepatology'
    get    'urology' => 'static_pages#urology'
    get    'vascularsurgery' => 'static_pages#vascularsurgery'
    get    'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    get    'userappointment' => 'users#appointment'

    resources :users 
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]


end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token, :activation_token, :reset_token
    before_save   :downcase_email
    before_create :create_activation_digest
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                         uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    class << self
        # Returns the hash digest of the given string.
        def digest(string)
            cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                          BCrypt::Engine.cost
            BCrypt::Password.create(string, cost: cost)
        end

        # Returns a random token.
        def new_token
            SecureRandom.urlsafe_base64
        end
    end


    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
    end

    # Activates an account.
    def activate
        update_columns(activated: true, activated_at: Time.zone.now)
    end

    # Sends activation email.
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end

    # Sets the password reset attributes.
    def create_reset_digest
        self.reset_token = User.new_token
        update_columns(reset_digest:  User.digest(reset_token), reset_sent_at: Time.zone.now)
    end

    # Sends password reset email.
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    # Returns true if a password reset has expired.
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end


    private

    # Converts email to all lower-case.
    def downcase_email
        self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
        self.activation_token  = User.new_token
        self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
    :following, :followers]
    before_action :correct_user,   only: [:edit, :update]
    before_action :admin_user,     only: :destroy


 def index
     @users = User.where(activated: true).paginate(page: params[:page])
 end

 def show
     @user = User.find(params[:id])
     redirect_to root_url and return unless @user.activated?
 end

 def new
     @user = User.new
 end

 def create
     @user = User.new(user_params)
     if @user.save
         @user.send_activation_email
         flash[:info] = "Please check your email to activate your account."
         redirect_to root_url
         else
         render 'new'
     end
 end

 def edit
     @user = User.find(params[:id])
 end

 def update
     @user = User.find(params[:id])
     if @user.update_attributes(user_params)
         flash[:success] = "Profile updated"
         redirect_to @user
         else
         render 'edit'
     end
 end

 def destroy
     User.find(params[:id]).destroy
     flash[:success] = "User deleted"
     redirect_to users_url
 end



 private

 def user_params
     params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
 end

 # Before filters

 # Confirms the correct user.
 def correct_user
     @user = User.find(params[:id])
     redirect_to(root_url) unless current_user?(@user)
 end

 # Confirms an admin user.
 def admin_user
     redirect_to(root_url) unless current_user.admin?
 end


end

app/helpers/users_helper.rb
module UsersHelper
    
    # Returns the Gravatar for the given user.
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/appointment.html.erb
<% provide(:title, "Make an appointment") %>
<html>
    
    <ul class="nav navbar-nav navbar-right">
        </ul>
    <body>
        <h1 style = "margin-top: 0px;">This is an Make an Appointment Page</h1>
        <div class = "invisibleblock"></div>
        <div  class = "appointmentframe"> 
        <div class = "appointmentheader">
        <li>Find a Doctor</li>
        <li>What specaity:</li>
       
        </div>
        
        </div>
        
    </body>
    
    
    
</html>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
      <p></p>
      <%= f.submit "Delete Account", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>


<html>
  
  <body>
    <div class = "userbackground">
    
    
      <div class ="usertitletab", style= "margin: 0 auto;">
        <div class = "usertab1">
          <%= link_to "Make an Appointment", userappointment_path %>
          
	       </div>
	       <div class = "usertab2">
 	   	    <h7>Send/Receive Message</h7>
 	       </div>
 	       <div class = "usertab3">
 	   	    <h7>Event</h7>
 	       </div>
 	     </div>
 	   <div class = "invisibleblock">
 	   </div>
 	   <p>
     <%= link_to image_tag("BridgeportMedicalCenter.png", alt: "Bridgeport Medical Center", width: "1100px", height: "350px", style: "display: block;   margin: 0 auto;") %>
    </p>
    
    
</div>
    
</body>
</html>