config/routes.rb
Rails.application.routes.draw do
    root                'static_pages#home'
    get    'help'    => 'static_pages#help'
    get    'about'   => 'static_pages#about'
    get    'aboutus' => 'static_pages#aboutus'
    get    'contact' => 'static_pages#contact'
    get    'allergyimmunology'   => 'static_pages#allergyimmunology'
    get    'anatomicpathology' => 'static_pages#anatomicpathology'
    get    'anatomicclinicalpathology' => 'static_pages#anatomicclinicalpathology'
    get    'anesthesiology' => 'static_pages#anesthesiology'
    get    'bariatricsurgery' => 'static_pages#bariatricsurgery'
    get    'breastsurgery' => 'static_pages#breastsurgery'
    get    'cardiacsurgery' => 'static_pages#cardiacsurgery'
    get    'cardiovasculardisease' => 'static_pages#cardiovasculardisease'
    get    'childadolescentpsychiatry' => 'static_pages#childadolescentpsychiatry'
    get    'childneurology'=> 'static_pages#childneurology'
    get    'clinicalcardiacelectrophysiology' => 'static_pages#clinicalcardiacelectrophysiology'
    get    'clinicalpathology' => 'static_pages#clinicalpathology'
    get    'colonrectalsurgery' => 'static_pages#colonrectalsurgery'
    get    'criticalcaremedicine' => 'static_pages#criticalcaremedicine'
    get    'dentistry' => 'static_pages#dentistry'
    get    'dermatology' => 'static_pages#dermatology'
    get    'diagnosticradiology'=> 'static_pages#diagnosticradiology'
    get    'emergencymedicalservices' => 'static_pages#emergencymedicalservices'
    get    'endocrinology'=> 'static_pages#endocrinology'
    get    'facialplasticreconstrsurgery'=> 'static_pages#facialplasticreconstrsurgery'
    get    'familymedicine' => 'static_pages#familymedicine'
    get    'gastroenterology' => 'static_pages#gastroenterology'
    get    'generalsurgery' => 'static_pages#generalsurgery'
    get    'geriatricmedicine' => 'static_pages#geriatricmedicine'
    get    'gynecologiconcology' => 'static_pages#gynecologiconcology'
    get    'gynecology'=> 'static_pages#gynecology'
    get    'handsurgery'=> 'static_pages#handsurgery'
    get    'headnecksurgery'=> 'static_pages#headnecksurgery'
    get    'hematology'=> 'static_pages#hematology'
    get    'hospiceandpalliativemedicine'=> 'static_pages#hospiceandpalliativemedicine'
    get    'hyperbaricmedicine' => 'static_pages#hyperbaricmedicine'
    get    'infectiousdisease' => 'static_pages#infectiousdisease'
    get    'integrativemedicine'=> 'static_pages#integrativemedicine'
    get    'internalmedicine' => 'static_pages#internalmedicine'
    get    'interventionalcardiology' => 'static_pages#interventionalcardiology'
    get    'maternalfetalmedicine' => 'static_pages#maternalfetalmedicine'
    get    'medicaloncology' => 'static_pages#medicaloncology'
    get    'neonatalperinatalmedicine'=> 'static_pages#neonatalperinatalmedicine'
    get    'nephrology' => 'static_pages#nephrology'
    get    'neurologicalsurgery' => 'static_pages#neurologicalsurgery'
    get    'neurology' => 'static_pages#neurology'
    get    'neuroradiology'=> 'static_pages#neuroradiology'
    get    'nuclearmedicine' => 'static_pages#nuclearmedicine'
    get    'obstetrics' => 'static_pages#obstetrics'
    get    'occupationalmedicine' => 'static_pages#occupationalmedicine'
    get    'ophthalmology' => 'static_pages#ophthalmology'
    get    'oralmaxillofacialsurgery' => 'static_pages#oralmaxillofacialsurgery'
    get    'orthopaedicsurgery' =>  'static_pages#orthopaedicsurgery'
    get    'otolaryngology' => 'static_pages#otolaryngology'
    get    'painmedicinepainmanagement' => 'static_pages#painmedicinepainmanagement'
    get    'pathology' => 'static_pages#pathology'
    get    'pediatricallergyimmunology' => 'static_pages#pediatricallergyimmunology'
    get    'pediatriccardiology' => 'static_pages#pediatriccardiology'
    get    'pediatricdentistry' => 'static_pages#pediatricdentistry'
    get    'pediatricdermatology' => 'static_pages#pediatricdermatology'
    get    'pediatricendocrinology' => 'static_pages#pediatricendocrinology'
    get    'pediatricinfectiousdisease' => 'static_pages#pediatricinfectiousdisease'
    get    'pediatricophthalmology' => 'static_pages#pediatricophthalmology'
    get    'pediatricpulmonology' => 'static_pages#pediatricpulmonology'
    get    'pediatricradiology' => 'static_pages#pediatricradiology'
    get    'pediatricsurgery' => 'static_pages#pediatricsurgery'
    get    'pediatricUrology' => 'static_pages#pediatricUrology'
    get    'pediatrics' => 'static_pages#pediatrics'
    get    'physicalmedicinerehabilitation' => 'static_pages#physicalmedicinerehabilitation'
    get    'plasticreconstructivesurgery' => 'static_pages#plasticreconstructivesurgery'
    get    'podiatry' => 'static_pages#podiatry'
    get    'psychiatry' => 'static_pages#psychiatry'
    get    'pulmonarydiseasemedicine' => 'static_pages#pulmonarydiseasemedicine'
    get    'radiationoncology' => 'static_pages#radiationoncology'
    get    'radiology' => 'static_pages#radiology'
    get    'radiologyneurointerventional' => 'static_pages#radiologyneurointerventional'
    get    'radiologyvascularinterventional' => 'static_pages#radiologyvascularinterventional'
    get    'reproductiveendocrinology' => 'static_pages#reproductiveendocrinology'
    get    'retinaspecialist' => 'static_pages#retinaspecialist'
    get    'rheumatology' => 'static_pages#rheumatology'
    get    'sleepmedicine' => 'static_pages#sleepmedicine'
    get    'spinesurgery' => 'static_pages#spinesurgery'
    get    'sportsmedicine' => 'static_pages#sportsmedicine'
    get    'surgicalcriticalcare' => 'static_pages#surgicalcriticalcare'
    get    'surgicaloncology' => 'static_pages#surgicaloncology'
    get    'thoracicsurgery' => 'static_pages#thoracicsurgery'
    get    'transplanthepatology' => 'static_pages#transplanthepatology'
    get    'urology' => 'static_pages#urology'
    get    'vascularsurgery' => 'static_pages#vascularsurgery'
    get    'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    get    'userappointment' => 'users#appointment'

    resources :users 
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]


end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class ="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Bridgeport Medical Center</a>
    by <a href="http://www.railstutorial.org/">Stephan White & Mohammed Ali</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

  <div class="container">

    <%= link_to "Bridgeport Medical Center", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        
        <% if logged_in? %>
          
         
          
          <li><%= link_to "Users", users_path %></li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>


  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}", style: "top= 20px;") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>

    </div>



  </body>


</html>